// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB7Iuzz2GT9qUpiDAbv8CKU3OfdtaGtd8',
    appId: '1:158223825544:web:7881d3b2aae908f9117d3d',
    messagingSenderId: '158223825544',
    projectId: 'shox-bebd7',
    authDomain: 'shox-bebd7.firebaseapp.com',
    storageBucket: 'shox-bebd7.appspot.com',
    measurementId: 'G-24Q33X9VB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5VsJqlwvnDapCtYU9tMfbr-_YNpalDNc',
    appId: '1:158223825544:android:b461e7224efdd7ab117d3d',
    messagingSenderId: '158223825544',
    projectId: 'shox-bebd7',
    storageBucket: 'shox-bebd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83YvenXvAEQZAuJf-f570Nv_yCnhTjNs',
    appId: '1:158223825544:ios:8ea84c1887854140117d3d',
    messagingSenderId: '158223825544',
    projectId: 'shox-bebd7',
    storageBucket: 'shox-bebd7.appspot.com',
    androidClientId: '158223825544-8req8rf97073318agdb0rkvjt7komhr7.apps.googleusercontent.com',
    iosClientId: '158223825544-rdbsqsqq8l7chmdjip79b7kjrgja7nem.apps.googleusercontent.com',
    iosBundleId: 'com.ndn21.shox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB83YvenXvAEQZAuJf-f570Nv_yCnhTjNs',
    appId: '1:158223825544:ios:286bf37f80941752117d3d',
    messagingSenderId: '158223825544',
    projectId: 'shox-bebd7',
    storageBucket: 'shox-bebd7.appspot.com',
    androidClientId: '158223825544-8req8rf97073318agdb0rkvjt7komhr7.apps.googleusercontent.com',
    iosClientId: '158223825544-q7dkph3b493252kuano61rg65jhdmanv.apps.googleusercontent.com',
    iosBundleId: 'com.example.shox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB7Iuzz2GT9qUpiDAbv8CKU3OfdtaGtd8',
    appId: '1:158223825544:web:87cb41878e1e1f4d117d3d',
    messagingSenderId: '158223825544',
    projectId: 'shox-bebd7',
    authDomain: 'shox-bebd7.firebaseapp.com',
    storageBucket: 'shox-bebd7.appspot.com',
    measurementId: 'G-G3PFL2S4BR',
  );
}
